
let defs=[],current=null;
const $=s=>document.querySelector(s), storeKey="shuddhoAssessmentsV5";
fetch("./assessments.json").then(r=>r.json()).then(d=>{defs=d;drawCards()});
function drawCards(){ $("#cards").innerHTML=defs.map(a=>`<button class="card tool-card" data-id="${a.id}"><h3>${a.en}</h3><p>${a.bn}</p><span class="chip">${a.qs.length} questions</span></button>`).join("");document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>openAssessment(b.dataset.id))}
function openAssessment(id){current=defs.find(x=>x.id===id);$("#cards").hidden=true;$("#runner").hidden=false;$("#title").innerHTML=`${current.en}<br><small>${current.bn}</small>`;$("#form").innerHTML=current.qs.map(q=>`<div class="field"><label>${q[1]}<br><small>${q[2]}</small></label><input name="${q[0]}" type="number" min="${q[3]}" max="${q[4]}" step="any" required></div>`).join("");$("#result").innerHTML=""}
$("#back").onclick=()=>{$("#runner").hidden=true;$("#cards").hidden=false};
function calc(a,v){
 let risk=0,strengths=[],weak=[];
 const add=(cond,pts,good,bad)=>{if(cond){risk+=pts;weak.push(bad)}else strengths.push(good)};
 if(a.id==="general"){add(v.activity<3,20,"Regular activity","Low activity");add(v.sleep<7||v.sleep>9,18,"Sleep duration","Sleep duration");add(v.fruitveg<4,16,"Fruit/vegetable intake","Low produce intake");add(v.stress>6,18,"Stress control","High stress");add(v.smoking>0,28,"Non-smoking","Smoking")}
 else if(a.id==="metabolic"){add(v.waist>=50,24,"Waist ratio","Central adiposity");add(v.activity<3,18,"Activity","Low activity");add(v.sleep<7,14,"Sleep","Short sleep");add(v.glucose>=100,24,"Fasting glucose","Higher glucose");add(v.family>0,20,"No family-history flag","Family history")}
 else if(a.id==="diabetes"){add(v.age>=45,15,"Younger age","Age-related risk");add(v.bmi>=25,22,"BMI below 25","Higher BMI");add(v.activity<3,18,"Activity","Low activity");add(v.family>0,20,"No family-history flag","Family history");add(v.history>0,25,"No prior high-glucose flag","Prior high glucose")}
 else if(a.id==="cardio"){add(v.sbp>=130,28,"Blood pressure","Higher systolic BP");add(v.smoking>0,24,"Non-smoking","Smoking");add(v.activity<3,16,"Activity","Low activity");add(v.sleep<7,12,"Sleep","Short sleep");add(v.nonhdl>=160,20,"Non-HDL","Higher non-HDL")}
 else if(a.id==="kidney"){add(v.egfr<60,30,"eGFR","Lower eGFR");add(v.uacr>=30,25,"UACR","Albuminuria signal");add(v.diabetes>0,18,"No diabetes flag","Diabetes");add(v.sbp>=130,15,"Blood pressure","Higher BP");add(v.nsaid>0,12,"Low NSAID exposure","Frequent NSAID use")}
 else if(a.id==="gut"){add(v.fiber<25,20,"Fiber","Low fiber");add(v.plants<20,18,"Plant diversity","Low plant diversity");add(v.bowel<6,20,"Bowel comfort","Poor bowel comfort");add(v.bloating>5,20,"Low bloating burden","Frequent bloating");add(v.fermented<2,10,"Fermented-food variety","Low fermented-food intake")}
 else if(a.id==="sleep"){add(v.sleep<7||v.sleep>9,22,"Sleep duration","Sleep duration");add(v.quality<6,20,"Sleep quality","Poor sleep quality");add(v.energy<6,18,"Daytime energy","Low daytime energy");add(v.screen>1,15,"Low pre-bed screen","High pre-bed screen");add(v.snore>0,25,"No snoring flag","Snoring")}
 else if(a.id==="hydration"){add(v.water<1500,25,"Fluid intake","Low fluid intake");add(v.urine>=6,25,"Urine color","Dark urine");add(v.heat>0&&v.water<2500,25,"Heat hydration","Heat/sweat without extra fluid");add(v.thirst>0,25,"Low thirst burden","Frequent thirst")}
 else if(a.id==="muscle"){add(v.age>=65,15,"Age-related reserve","Age-related muscle risk");add(v.protein/Math.max(1,v.weight)<1,30,"Protein adequacy","Low protein/kg");add(v.strength<2,25,"Strength activity","Low strength training");add(v.loss>=5,30,"Weight stability","Recent weight loss")}
 else if(a.id==="women"){add(v.cycle<6,20,"Cycle regularity","Cycle irregularity");add(v.sleep<7,18,"Sleep","Short sleep");add(v.activity<3,16,"Activity","Low activity");add(v.iron<3,16,"Iron-rich foods","Low iron-rich foods");add(v.symptoms>6,30,"Low symptom burden","Higher symptom burden")}
 else if(a.id==="nutrition"){add(v.fruitveg<4,20,"Produce intake","Low produce intake");add(v.protein<2,18,"Protein-rich meals","Low protein meal frequency");add(v.whole<2,16,"Whole foods","Low whole grain/legume intake");add(v.ultra>2,23,"Low ultra-processed intake","Higher ultra-processed intake");add(v.sugary>3,23,"Low sugary-drink intake","Frequent sugary drinks")}
 else if(a.id==="supplement"){add(v.count>5,18,"Simple supplement routine","Many supplements");add(v.reason<7,18,"Clear reasons","Unclear reasons");add(v.interaction<1,24,"Interaction check","Interactions not checked");add(v.dose<1,18,"Dose knowledge","Dose unclear");add(v.review<1,22,"Professional review","No professional review")}
 risk=Math.min(100,risk);
 return {risk,strengths:[...new Set(strengths)].slice(0,4),weak:[...new Set(weak)].slice(0,4)};
}
$("#submit").onclick=e=>{e.preventDefault();if(!current)return;const fd=new FormData($("#form")),v={};for(const [k,val] of fd)v[k]=Number(val);const r=calc(current,v),band=r.risk<25?["Good / Lower concern","good"]:r.risk<50?["Moderate",""]:r.risk<75?["Needs attention","warn"]:["High concern","bad"];const suggestions=r.weak.map(x=>`<li>Focus on: ${x}. Start with one realistic change and reassess after a few weeks.</li>`).join("")||"<li>Maintain current healthy habits and keep tracking trends.</li>";$("#result").innerHTML=`<div class="result"><div class="score ${band[1]}">${100-r.risk}/100</div><h3>${band[0]}</h3><p>This is an educational lifestyle/health profile, not a diagnosis.</p><div class="grid2"><div><h3>Strengths</h3><ul>${r.strengths.map(x=>`<li>${x}</li>`).join("")||"<li>No clear strength signal yet.</li>"}</ul></div><div><h3>Priority areas</h3><ul>${r.weak.map(x=>`<li>${x}</li>`).join("")||"<li>No major flag from these questions.</li>"}</ul></div></div><h3>Suggestions</h3><ul>${suggestions}</ul><p><a href="../dashboard/">View in Health Dashboard →</a></p></div>`;let all={};try{all=JSON.parse(localStorage.getItem(storeKey)||"{}")}catch(e){}all[current.id]={name:current.en,score:100-r.risk,status:band[0],date:new Date().toISOString(),weak:r.weak,strengths:r.strengths};localStorage.setItem(storeKey,JSON.stringify(all))}
